ALTER TABLE verification_codes
	ADD COLUMN entity_id VARCHAR(36) NOT NULL,
	ADD COLUMN entity_type VARCHAR(20) NOT NULL AFTER entity_id,
	ADD COLUMN contact VARCHAR(255) NOT NULL,
  	ADD COLUMN channel VARCHAR(20) NOT NULL,  
  	ADD COLUMN verified BOOLEAN NOT NULL,
  	MODIFY COLUMN expires_at TIMESTAMP NOT NULL,
  	MODIFY COLUMN created_at TIMESTAMP NOT NULL,   
  	ADD COLUMN updated_at TIMESTAMP NOT NULL,
  	DROP COLUMN phone;
    