// Code generated by mockery v2.53.6. DO NOT EDIT.

package operating_hour

import (
	context "context"

	domain "github.com/arizaguaca/qhay-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// OperatingHourRepository is an autogenerated mock type for the OperatingHourRepository type
type OperatingHourRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, hour
func (_m *OperatingHourRepository) Create(ctx context.Context, hour *domain.OperatingHour) error {
	ret := _m.Called(ctx, hour)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.OperatingHour) error); ok {
		r0 = rf(ctx, hour)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *OperatingHourRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByRestaurantAndDay provides a mock function with given fields: ctx, restaurantID, day
func (_m *OperatingHourRepository) GetByRestaurantAndDay(ctx context.Context, restaurantID string, day int) (*domain.OperatingHour, error) {
	ret := _m.Called(ctx, restaurantID, day)

	if len(ret) == 0 {
		panic("no return value specified for GetByRestaurantAndDay")
	}

	var r0 *domain.OperatingHour
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*domain.OperatingHour, error)); ok {
		return rf(ctx, restaurantID, day)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *domain.OperatingHour); ok {
		r0 = rf(ctx, restaurantID, day)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.OperatingHour)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, restaurantID, day)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByRestaurantID provides a mock function with given fields: ctx, restaurantID
func (_m *OperatingHourRepository) GetByRestaurantID(ctx context.Context, restaurantID string) ([]*domain.OperatingHour, error) {
	ret := _m.Called(ctx, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for GetByRestaurantID")
	}

	var r0 []*domain.OperatingHour
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.OperatingHour, error)); ok {
		return rf(ctx, restaurantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.OperatingHour); ok {
		r0 = rf(ctx, restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.OperatingHour)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, restaurantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, hour
func (_m *OperatingHourRepository) Update(ctx context.Context, hour *domain.OperatingHour) error {
	ret := _m.Called(ctx, hour)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.OperatingHour) error); ok {
		r0 = rf(ctx, hour)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOperatingHourRepository creates a new instance of OperatingHourRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperatingHourRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OperatingHourRepository {
	mock := &OperatingHourRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
