// Code generated by mockery v2.53.6. DO NOT EDIT.

package qrcode

import (
	context "context"

	domain "github.com/arizaguaca/qhay-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// QRCodeRepository is an autogenerated mock type for the QRCodeRepository type
type QRCodeRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, qrCode
func (_m *QRCodeRepository) Create(ctx context.Context, qrCode *domain.QRCode) error {
	ret := _m.Called(ctx, qrCode)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.QRCode) error); ok {
		r0 = rf(ctx, qrCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *QRCodeRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *QRCodeRepository) GetByID(ctx context.Context, id string) (*domain.QRCode, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.QRCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.QRCode, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.QRCode); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.QRCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByRestaurantID provides a mock function with given fields: ctx, restaurantID
func (_m *QRCodeRepository) GetByRestaurantID(ctx context.Context, restaurantID string) ([]*domain.QRCode, error) {
	ret := _m.Called(ctx, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for GetByRestaurantID")
	}

	var r0 []*domain.QRCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.QRCode, error)); ok {
		return rf(ctx, restaurantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.QRCode); ok {
		r0 = rf(ctx, restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.QRCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, restaurantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTableNumber provides a mock function with given fields: ctx, restaurantID, tableNumber
func (_m *QRCodeRepository) GetByTableNumber(ctx context.Context, restaurantID string, tableNumber int) (*domain.QRCode, error) {
	ret := _m.Called(ctx, restaurantID, tableNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetByTableNumber")
	}

	var r0 *domain.QRCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*domain.QRCode, error)); ok {
		return rf(ctx, restaurantID, tableNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *domain.QRCode); ok {
		r0 = rf(ctx, restaurantID, tableNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.QRCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, restaurantID, tableNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQRCodeRepository creates a new instance of QRCodeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQRCodeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *QRCodeRepository {
	mock := &QRCodeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
