// Code generated by mockery v2.53.6. DO NOT EDIT.

package verification

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VerificationUsecase is an autogenerated mock type for the VerificationUsecase type
type VerificationUsecase struct {
	mock.Mock
}

// SendCode provides a mock function with given fields: ctx, phone
func (_m *VerificationUsecase) SendCode(ctx context.Context, phone string) error {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for SendCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, phone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyCode provides a mock function with given fields: ctx, phone, code
func (_m *VerificationUsecase) VerifyCode(ctx context.Context, phone string, code string) (string, error) {
	ret := _m.Called(ctx, phone, code)

	if len(ret) == 0 {
		panic("no return value specified for VerifyCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, phone, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, phone, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, phone, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVerificationUsecase creates a new instance of VerificationUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerificationUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerificationUsecase {
	mock := &VerificationUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
