// Code generated by mockery v2.53.6. DO NOT EDIT.

package verification

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SMSService is an autogenerated mock type for the SMSService type
type SMSService struct {
	mock.Mock
}

// SendSMS provides a mock function with given fields: ctx, phone, message
func (_m *SMSService) SendSMS(ctx context.Context, phone string, message string) error {
	ret := _m.Called(ctx, phone, message)

	if len(ret) == 0 {
		panic("no return value specified for SendSMS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, phone, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSMSService creates a new instance of SMSService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSMSService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SMSService {
	mock := &SMSService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
