// Code generated by mockery v2.53.6. DO NOT EDIT.

package verification

import (
	context "context"

	domain "github.com/arizaguaca/qhay-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// VerificationRepository is an autogenerated mock type for the VerificationRepository type
type VerificationRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, verify
func (_m *VerificationRepository) Create(ctx context.Context, verify *domain.VerificationCode) error {
	ret := _m.Called(ctx, verify)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.VerificationCode) error); ok {
		r0 = rf(ctx, verify)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByPhone provides a mock function with given fields: ctx, phone
func (_m *VerificationRepository) DeleteByPhone(ctx context.Context, phone string) error {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByPhone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, phone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLatestByPhone provides a mock function with given fields: ctx, phone
func (_m *VerificationRepository) GetLatestByPhone(ctx context.Context, phone string) (*domain.VerificationCode, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestByPhone")
	}

	var r0 *domain.VerificationCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.VerificationCode, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.VerificationCode); ok {
		r0 = rf(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.VerificationCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVerificationRepository creates a new instance of VerificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerificationRepository {
	mock := &VerificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
