// Code generated by mockery v2.53.6. DO NOT EDIT.

package restaurant

import (
	context "context"

	domain "github.com/arizaguaca/qhay-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// RestaurantUsecase is an autogenerated mock type for the RestaurantUsecase type
type RestaurantUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *RestaurantUsecase) Create(ctx context.Context, _a1 *domain.Restaurant) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Restaurant) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx
func (_m *RestaurantUsecase) Fetch(ctx context.Context) ([]*domain.Restaurant, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []*domain.Restaurant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Restaurant, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Restaurant); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Restaurant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *RestaurantUsecase) GetByID(ctx context.Context, id string) (*domain.Restaurant, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Restaurant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Restaurant, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Restaurant); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Restaurant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByOwnerID provides a mock function with given fields: ctx, ownerID
func (_m *RestaurantUsecase) GetByOwnerID(ctx context.Context, ownerID string) ([]*domain.Restaurant, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByOwnerID")
	}

	var r0 []*domain.Restaurant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Restaurant, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Restaurant); ok {
		r0 = rf(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Restaurant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *RestaurantUsecase) Update(ctx context.Context, _a1 *domain.Restaurant) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Restaurant) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRestaurantUsecase creates a new instance of RestaurantUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRestaurantUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RestaurantUsecase {
	mock := &RestaurantUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
